# Generated by Django 4.1.2 on 2022-11-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFacePlant', '0005_post_likecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
    ]
